# https://wiki.archlinux.org/title/PipeWire#Low_audio_quality_on_Bluetooth

monitor.bluez.properties = {
  bluez5.enable-sbc-xq = true
  bluez5.enable-msbc = true
  #bluez5.codecs = [ sbc sbc_xq ldap aac ]
  #bluez5.codecs = [ sbc sbc_xq aac ldac aptx aptx_hd aptx_ll aptx_ll_duplex faststream faststream_duplex ]
  bluez5.autoswitch-profile = false
  bluez5.a2dp.ldac.quality = "hq"
  bluez5.auto-connect = [ hfp_hf hsp_hs hfp_ag hsp_ag ]
  bluez5.media-source-role = "playback"
}

